---
title: Upside-Down-Diffusion - a Hugging Face Space by AP123
description: Discover amazing ML apps made by the community
url: https://huggingface.co/spaces/AP123/Upside-Down-Diffusion
timestamp: 2025-01-20T15:44:55.487Z
domain: huggingface.co
path: spaces_AP123_Upside-Down-Diffusion
---

# Upside-Down-Diffusion - a Hugging Face Space by AP123


Discover amazing ML apps made by the community


## Content

Fetching metadata from the HF Docker repository...

runtime error
-------------

lder = snapshot\_download( File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/utils/\_validators.py", line 118, in \_inner\_fn return fn(\*args, \*\*kwargs) File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/\_snapshot\_download.py", line 236, in snapshot\_download \_inner\_hf\_hub\_download(file) File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/\_snapshot\_download.py", line 213, in \_inner\_hf\_hub\_download return hf\_hub\_download( File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/utils/\_validators.py", line 118, in \_inner\_fn return fn(\*args, \*\*kwargs) File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/file\_download.py", line 1461, in hf\_hub\_download http\_get( File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/file\_download.py", line 468, in http\_get r = \_request\_wrapper( File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/file\_download.py", line 425, in \_request\_wrapper response = get\_session().request(method=method, url=url, \*\*params) File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, \*\*send\_kwargs) File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, \*\*kwargs) File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\_hub/utils/\_http.py", line 63, in send return super().send(request, \*args, \*\*kwargs) File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/adapters.py", line 532, in send raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='hf.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 362a6c0f-f635-4b1d-85d5-2ce34010cb16)')
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Container logs:

## Metadata

```json
{
  "title": "Upside-Down-Diffusion - a Hugging Face Space by AP123",
  "description": "Discover amazing ML apps made by the community",
  "url": "https://huggingface.co/spaces/AP123/Upside-Down-Diffusion",
  "content": "Fetching metadata from the HF Docker repository...\n\nruntime error\n-------------\n\nlder = snapshot\\_download( File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/utils/\\_validators.py\", line 118, in \\_inner\\_fn return fn(\\*args, \\*\\*kwargs) File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/\\_snapshot\\_download.py\", line 236, in snapshot\\_download \\_inner\\_hf\\_hub\\_download(file) File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/\\_snapshot\\_download.py\", line 213, in \\_inner\\_hf\\_hub\\_download return hf\\_hub\\_download( File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/utils/\\_validators.py\", line 118, in \\_inner\\_fn return fn(\\*args, \\*\\*kwargs) File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/file\\_download.py\", line 1461, in hf\\_hub\\_download http\\_get( File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/file\\_download.py\", line 468, in http\\_get r = \\_request\\_wrapper( File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/file\\_download.py\", line 425, in \\_request\\_wrapper response = get\\_session().request(method=method, url=url, \\*\\*params) File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request resp = self.send(prep, \\*\\*send\\_kwargs) File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send r = adapter.send(request, \\*\\*kwargs) File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface\\_hub/utils/\\_http.py\", line 63, in send return super().send(request, \\*args, \\*\\*kwargs) File \"/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/adapters.py\", line 532, in send raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: (ReadTimeoutError(\"HTTPSConnectionPool(host='hf.co', port=443): Read timed out. (read timeout=10)\"), '(Request ID: 362a6c0f-f635-4b1d-85d5-2ce34010cb16)')\n------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\nContainer logs:",
  "usage": {
    "tokens": 679
  }
}
```
